apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: redis
spec:
  hard:
    requests.cpu: 1000m
    requests.memory: 2Gi
    limits.cpu: 4000m
    limits.memory: 10Gi
    requests.storage: 20Gi
