apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: redis
spec:
  hard:
    requests.cpu: 3000m
    requests.memory: 6Gi
    limits.cpu: 12000m
    limits.memory: 24Gi
    requests.storage: 30Gi
