apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: redis
spec:
  hard:
    requests.cpu: 4000m
    requests.memory: 8Gi
    limits.cpu: 12000m
    limits.memory: 24Gi
    requests.storage: 60Gi
