apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: redis
spec:
  hard:
    requests.cpu: 100m
    requests.memory: 256Mi
    limits.cpu: 200m
    limits.memory: 512Mi
    requests.storage: 50Gi
    persistentvolumeclaims: "3"
    pods: "10"
    configmaps: "10"
    secrets: "10"
    services: "5"
    services.loadbalancers: "0"
