apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: redis
spec:
  hard:
    requests.cpu: 500m
    requests.memory: 1Gi
    limits.cpu: 1000m
    limits.memory: 2Gi
    requests.storage: 10Gi
    persistentvolumeclaims: "5"
    pods: "20"
    configmaps: "20"
    secrets: "20"
    services: "20"
    services.loadbalancers: "0"
