name: push tags branches

on:
  push:
    tags:
      - "*"

jobs:
  apply:
    name: Set namespace
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Apply kustomize
        env:
          KUBE_CONFIG_DATA: ${{ secrets.TKE_CONFIG_DATA }}
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 -d > /tmp/config
          export KUBECONFIG=/tmp/config
          kustomize build overlays/production | kubectl apply -f -
